import "react-toastify/dist/ReactToastify.css";
import "./assets/globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";

import FacebookIcon from "@/app/components/common/presentational/iconFactory/FacebookIcon/component";
import TwitterIcon from "@/app/components/common/presentational/iconFactory/TwitterIcon/component";
import YouTubeIcon from "@/app/components/common/presentational/iconFactory/YouTubeIcon/component";
import NavBar from "@/app/components/compound/NavBar";

import Providers from "./providers/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Wet Pages",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="dracula" lang="en">
      <body className={inter.className}>
        <Providers>
          <>
            <NavBar />
            <ToastContainer />
            {children}
            <footer className="footer footer-center p-10 bg-base-200 text-base-content rounded mt-8">
              <nav className="grid grid-flow-col gap-4">
                <a className="link link-hover">About us</a>
                <a className="link link-hover">Contact</a>
                <a className="link link-hover">Buy the Devs a Coffee</a>
                <a className="link link-hover">Advertising</a>
              </nav>
              <nav>
                <div className="grid grid-flow-col gap-4">
                  <a>
                    <TwitterIcon />
                  </a>
                  <a>
                    <YouTubeIcon />
                  </a>
                  <a>
                    <FacebookIcon />
                  </a>
                </div>
              </nav>
              <aside>
                <p>
                  Copyright © 2024 - All right reserved by American Made Code
                  LLC
                </p>
              </aside>
            </footer>
          </>
        </Providers>
      </body>
    </html>
  );
}
