import "react-toastify/dist/ReactToastify.css";
import "../styling/globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";

import FacebookIcon from "@/components/common/icons/FacebookIcon";
import TwitterIcon from "@/components/common/icons/TwitterIcon";
import YouTubeIcon from "@/components/common/icons/YouTubeIcon";

import Providers from "../providers/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Agent Hackathon Boilerplate",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="dracula" lang="en">
      <body className={inter.className}>
        <Providers>
          <>
            <ToastContainer />
            <div className="h-screen">{children}</div>
          </>
        </Providers>
      </body>
    </html>
  );
}
